spring:
  application:
    name: notification-service
  data:
    redis:
      host: notification-redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: inventoryReserved:com.sentinel.notification_service.event.InventoryReservedEvent,inventoryRejected:com.sentinel.notification_service.event.InventoryRejectedEvent

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name}
        environment: ${spring.profiles.active:default}