spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://order-service:8080}
              predicates:
                - Path=/orders/**
            - id: inventory-service
              uri: ${INVENTORY_SERVICE_URL:http://inventory-service:8080}
              predicates:
                - Path=/inventory/**
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8080}
              predicates:
                - Path=/notifications/**

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name}
        environment: ${spring.profiles.active:default}