spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: http://order-service:8080
              predicates:
                - Path=/orders/**
            - id: inventory-service
              uri: http://inventory-service:8080
              predicates:
                - Path=/inventory/**
            - id: notification-service
              uri: http://notification-service:8080
              predicates:
                - Path=/notifications/**